LangChain: Not ready for Python 3.12 yet, because it needs `aiohttp`
aiohttp/_websocket.c:3042:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
[...]

ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects