Npgsql: Remove testing on .NET 8.x
Error: /usr/share/dotnet/sdk/9.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(266,5):

error NETSDK1005: Assets file '/home/runner/work/cratedb-examples/cratedb-examples/by-language/csharp-npgsql/obj/project.assets.json' doesn't have a target for 'net8.0'. Ensure that restore has run and that you have included 'net8.0' in the TargetFrameworks for your project. [/home/runner/work/cratedb-examples/cratedb-examples/by-language/csharp-npgsql/demo.csproj]