PyCaret: Adjustments for MLflow 3.10.2
WARNING mlflow.models.model: `artifact_path` is deprecated.
Please use `name` instead.

mlflow.exceptions.MlflowException: Invalid model name
('model/classification_model') provided.
Model name must be a non-empty string and cannot contain the following
characters: ('/', ':', '.', '%', '"', "'")